name: Publish to Extension Marketplace

on:
  release:
    types: [published]

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run publish
        env:
          CI: true
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}